### ISSUE TITLE
Still white block at bottom on large screens

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#114]
### **What is the issue?**

The landing page has a white block at the bottom on large screens (chrome)

### Expected Behaviour

The bottom should be completely blue

### Actual Behaviour

See issue

### Steps to reproduce

Chrome on a 2K display full screen. Perhaps zoom out a bit. It should be easy to reproduce.

**Comment by northdpole** [comment]
fixed by #120
