### ISSUE TITLE
Path collisions because of casings

### ISSUE THREAD

**Issue by flowirtz** [OWASP/common-requirement-enumeration#143]
### **What is the issue?**

I just cloned the repository on Mac. I received the following warning during cloning:
```text
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'cres/Limit size and number of uploaded files.yaml'
  'cres/limit size and number of uploaded files.yaml'
  'cres/Log access to sensitive data.yaml'
  'cres/log access to sensitive data.yaml'
  'cres/Secure communication.yaml'
  'cres/secure communication.yaml'
  'cres/Secure User Management.yaml'
  'cres/Secure user management.yaml'
```

e.g.
- [`cres/Limit size and number of uploaded files.yaml`](https://github.com/OWASP/common-requirement-enumeration/blob/main/cres/Limit%20size%20and%20number%20of%20uploaded%20files.yaml), and
- [`cres/limit size and number of uploaded files.yaml`](https://github.com/OWASP/common-requirement-enumeration/blob/main/cres/limit%20size%20and%20number%20of%20uploaded%20files.yaml)

### Expected Behaviour

All files have unique paths irrespective of casing.

### Actual Behaviour

**Not** all files have unique paths irrespective of casing.

### Steps to reproduce

Run `gh repo clone OWASP/common-requirement-enumeration` on a Mac.

**Comment by northdpole** [comment]
thanks for that, seems we have old files in the /cre/ folder i'll clean them up

**Comment by northdpole** [comment]
this has been fixed for months, sorry for not closing it
