### ISSUE TITLE
Higher level topics search is slow

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#154]
## Issue
Higher level topics search is slow
### **What is the issue?**
When searching for higher level topics (searching for >>) or use the link on the homepage takes long
< answer here >

### Expected Behaviour
Results should be quick

### Actual Behaviour
Results are slow

### Steps to reproduce
Click https://www.opencre.org/search/%3E%3E

Perhaps we can cache this page as it is important

**Comment by northdpole** [comment]
fixed in https://github.com/OWASP/common-requirement-enumeration/pull/178
