### ISSUE TITLE
Data issue: Root CREs contain one rogue topic "http headers". Fixed. needs new import

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#185]
The Root CREs contains one rogue topic called "http headers". It's related to "Set sufficient anti-chaching headers" so it's conceptually a tag - but it's not under the 'tags' topic. AND it is related to only topic which usually is not the idea of tags. I think that "set sufficient anti-caching headers" (which is under "secure data store") should have been linked to the topic of "HTTP security headers". I have changed this in the sheets. A new import will fix it:
I changed "http headers" into "http security headers" for topic 473-758
and removed topic row 473-759 "http headers". In sheet 2.1. NOT in the sheet that says "do not edit" :)
and in sheet 2.2
It may seem a detail but now it confuses users of the root cre page.

**Comment by northdpole** [comment]
fixed and validated :)
