### ISSUE TITLE
Create smartlink feature that takes a CWE and then shows that CWE on OpenCRE and else forwards to Mitre

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#230]
Could we make an interface that takes a CWE number and if it's in CRE shows that page (like https://www.opencre.org/node/standard/CWE/section/79) and if it's not, it forwards to the page at mitre? That would be a nice use case for people to use that link instead of a direct link to mitre. Tools could link to it for example. 

This could be implemented in a generic way by using what is already there for deeplinks: eg https://www.opencre.org/deeplink/ASVS?section=v9.2.5
but instead call it smartlink, so 
https://www.opencre.org/smartlink/ASVS?section=v9.2.5
or
https://www.opencre.org/smartlink/CWE?section=79

**Comment by northdpole** [comment]
closed by https://github.com/OWASP/common-requirement-enumeration/pull/233
