### ISSUE TITLE
Add 27001 by glueing with the NIST mapping

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#234]
Use the mapping NIST 800-53 with 27001 to add 27001 to CRE.
https://csrc.nist.gov/CSRC/media/Publications/sp/800-53/rev-5/final/documents/sp800-53r5-to-iso-27001-mapping.docx

**Comment by northdpole** [comment]
closed by https://github.com/OWASP/common-requirement-enumeration/pull/246
