### ISSUE TITLE
[Migrated from integration-standards] Request to reference the OWASP Secure Headers Project 

### ISSUE THREAD

**Issue by northdpole** [OWASP/common-requirement-enumeration#251]
https://github.com/OWASP/www-project-integration-standards/issues/44

**Comment by northdpole** [comment]
@righettod could you give us some more information on how the secure headers project is structured?
We can reference the repository as a whole but that wouldn't be that useful to you as you would only get one reference. Do you happen to have individual links to specific items in secure headers? If yes, there are two ways we can do this:

1. [preferable]: You add references to opencre.org in your source material and we parse it to extract those references and keep the mappings up to date automatically
2. you add one file in your repository that references the CREs you want to map to and the links in your repository or your website/source material that you want those CREs pointing to, we parse the file all the same and automatically keep the mappings up to date.
What do you think?


@robvanderveer , what's your opinion?

**Comment by righettod** [comment]
Hi,

Thank you very much for the feedback.

The OSHP provide information, as well as reference json files (stable permanent URL), about HTTP response security headers to add and HTTP response headers remove. These files are automatically updated by CI/CD pipeline.

The OSHP provide also others material about HTTP security headers like framework, libraries in addition to usage statistics.

https://owasp.org/www-project-secure-headers/

I will work on way 1 you mentioned and keep you posted.

**Comment by northdpole** [comment]
Could you please make a minimal change and send me a link to the commit/PR
so I can see how your content and the link look like? Just in case I need
to adjust our parsers :)

**Comment by righettod** [comment]
I will do it and keep you posted 😃

**Comment by righettod** [comment]
Hi,

I submitted this [PR](https://github.com/OWASP/www-project-secure-headers/pull/124) to initiate the integration work. 

I have applied the information provided by this [OpenCRE document](https://github.com/OWASP/www-project-integration-standards/raw/master/writeups/CRE-Explained6.pdf).

We will wee if my modification will be correct as the OSHP site is auto-generated from MD to HTML by the foundation template system.

**Comment by northdpole** [comment]
Seems correct to me and works with our existing parsers. Fantastic work,
let me know when it's ready and I'll add your repo to the import job

**Comment by righettod** [comment]
Due to the way in which the HTML is rendered by the foundation scripts from the MD files, I must use HTML comment to add the `<div>`  for OpenCRE reference:

![image](https://user-images.githubusercontent.com/1573775/215295769-666924a3-63c2-4352-b722-5c52c1edf2e3.png)

I tried the following syntax:

```html
<!-- <div id=prevent-information-disclosure-via-http-headers-anchor class="ruletitle"></div> -->
```

So, I performed a second try in the following PR:

https://github.com/OWASP/www-project-secure-headers/pull/125

**Comment by righettod** [comment]
PR was merged and this is the HTML rendering:

![image](https://user-images.githubusercontent.com/1573775/215316519-3bf70642-6320-427d-b562-9ce2b693b47c.png)

Usage of HTML comment to insert the `<div>` is OK for us. Let's see if is is OK for the OpenCRE team 😃

**Comment by northdpole** [comment]
> disappointed_relieved Due to the way in which the HTML is rendered by the foundation scripts from the MD files, I must use HTML comment to add the `<div>` for OpenCRE reference:
> 
> ![image](https://user-images.githubusercontent.com/1573775/215295769-666924a3-63c2-4352-b722-5c52c1edf2e3.png)
> 
> computer I tried the following syntax:
> 
> ```
> 
> ```
> 
> arrow_right So, I performed a second try in the following PR:
> 
> [OWASP/www-project-secure-headers#125](https://github.com/OWASP/www-project-secure-headers/pull/125)
> 
> eyes It is still OK on your side with this syntax using HTML comment?
> 
Seems ok on our end, yes

> earth_americas The base URL to reference is the following, the index file is important otherwise the anchor do not work:
> 
> ```
> https://owasp.org/www-project-secure-headers/index.html
> ```
> 
> rotating_light By the way I have this error on OpenCRE URL:
> 
> ![image](https://user-images.githubusercontent.com/1573775/215295874-37e4cf31-a937-4be9-b4cc-75e168534aaf.png)
> 
> It is normal?
yes, I was moving the DNS of opencre.org from godaddy to cloudflare  and there was some brief, expected  downtime. But now we have a great CDN and analytics, for free!

**Comment by northdpole** [comment]
> PR was merged and this is the HTML rendering:
> 
> ![image](https://user-images.githubusercontent.com/1573775/215316519-3bf70642-6320-427d-b562-9ce2b693b47c.png)
> 
> Usage of HTML comment to insert the `<div>` is OK for us. Let's see if is is OK for the OpenCRE team smiley

it's perfect, adjusting parsers when I get a chance, you should see the results on opencre.org in a few days when I manage to make the PR :-)

**Comment by righettod** [comment]
Thank you very much 😃

**Comment by righettod** [comment]
Hi @northdpole 

Any news about the finalization of the integration ?

Thanks a lot in advance for your feedback 😃

**Comment by northdpole** [comment]
this is already in prod 
closing as fixed

**Comment by righettod** [comment]
Thank you very much
