### ISSUE TITLE
Urgent, for Mees: Improve the landing page content and look

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#31]
The current landing page text needs to be improved in content and looks. 
See for content, including hyperlinks: https://docs.google.com/document/d/1BqFwHYsA0R6DA_9HgdeBaoDGEp7a1jZhUHmH_MN5a_E/edit#heading=h.ozvtefgoah0x

**Comment by Meess** [comment]
Updated the content, see pull request: https://github.com/OWASP/common-requirement-enumeration/pull/66
Still TODO:
- Logo

I suggest doing the "look and feel" / styling at a later stage.

**Comment by Meess** [comment]
@robvanderveer this issue can be closed, correct?

**Comment by robvanderveer** [comment]
It can move to P3, but only after we fixed the fact that the bottom part of the screen is still white. And if I had to name one tweak: make the main title a bit smaller. It looks particularly oversized on phones.

**Comment by northdpole** [comment]
i'll take this on then, don't worry about hits anymore :)
