### ISSUE TITLE
Mees, please create the nested and grouped view

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#38]
See the CREdesign powerpoint for more details (specs in this issue prevail). Two things:
.
1)Group linked things(standards or topics) by link type, in this order (perhaps having the linktypes a lighter color, so the topic names stand out more):
a) linktype "Linked" (fyi these will be standards),
b) then "is part of" (fyi these are topics linked one level higher in the hierarchy, if any)
c) then "contains" (fyi these are topics linked one level lower in the hierarchy, if any)
d) then "related" (fyi these are topics cross-linked, if any)
.
2)Nest under "is part of" and "related" topics: the same  overview of things with link types for that  topic, and so on(recursively), excluding the "contains", indented.
.
Example 1:
CRE 482-866 "Encrypt personal data at rest"
..Linked: ASVS - V6.1.1
..Is part of: Securely store regulated data 

....Is part of:  Encrypt data at rest 
......Linked: CWE - 311: (Missing Encryption of Sensitive Data)
......Is part of:  Secure data storage
........Linked: OWASP Top 10 - A3 (Sensitive data exposure)
......Related: Cryptography

..Related: Personal data protection
 ....Linked: NIST SP800 53 -  SC11
.
Example 2:
CRE 538-304 "Encrypt data at rest”

..Linked: CWE - 311: (Missing Encryption of Sensitive Data)
    
..Is part of: Secure data storage
....Linked: OWASP Top 10 - A3 (Sensitive data exposure)

..Related: Cryptography

..Contains: Encryption algorithms
..Contains: Securely store regulated data
..Contains: Secrets shared with clients only for low risk

**Comment by northdpole** [comment]
@robvanderveer is this done?

**Comment by robvanderveer** [comment]
@northdpole Well, in a way, yes, as the remaining work has been put in new issues.

**Comment by Meess** [comment]
Things still to be done are put in a separate issue: https://github.com/OWASP/common-requirement-enumeration/issues/81
