### ISSUE TITLE
Mees, please build frontend on search function in backend (already merged)

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#39]
https://opencreorg.herokuapp.com/rest/v1/text_search?text=session
It returns things with that text(A) and the things linked to it(B). The idea is to first show only the things with the text(A) and allow the user to click on them, with the regular click behaviour. This ignores the B items. Later, they can be used in a function that expands them for example. Layout of the result page can be the same as a CRE  page.
Add an option "Text" to the dropdown of the search bar and make that the default one.

**Comment by Meess** [comment]
Fixed in https://github.com/OWASP/common-requirement-enumeration/pull/82
