### ISSUE TITLE
Mees, create two ways to link from an item. 

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#41]
An item can link to its cre page or to the hyperlink.
Clicking on the item name should go the cre page. After the item name, add a underlined text "(content") that links in a new tab to the hyperlink.
Example:   ASVS -V2.2.5 (content). 
Yes, you read it correctly: underlined. It's the only way I can think of that suggests it is a separate thing to click on. I'm open to suggestions.
Also when you click on an item to go to its CRE page, on that CRE page also show that content thing after the name.

**Comment by northdpole** [comment]
@robvanderveer , if i understand correctly, this is  conflicting with this change https://github.com/OWASP/common-requirement-enumeration/issues/42 , 

current behaviour is clicking on a standard links you to the external page, but clicking on a CRE links you to the internal CRE page.

Do you want something different?

**Comment by robvanderveer** [comment]
Discussed with Mees: clicking a linked item expands it in the same page with all the stuff that it is linked to, plus it shows the hyperlink, as URL, visible, to make clear that you can go to the content.

**Comment by Meess** [comment]
@robvanderveer With the current setup this is somewhat solved correct? We don't link directly to any external page anymore, all external links are shown as "Reference" when the dropdown is expanded or on the specific page for that standard / cre.

If you agree, please close the ticket or suggested an alternative solution
