### ISSUE TITLE
Urgent: make sure opencre.org is indexed by Google

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#43]
Currently our opencre.org cannot be found if you search "common requirement enumeration" in google. We need to find out how to make it work. Maybe it's because of the way we forward to the heroku app?

**Comment by northdpole** [comment]
added to google indexing, it would make sense to fix the mobile view as well in the meantime

**Comment by northdpole** [comment]
give it a day or two and it should show up on search results

**Comment by northdpole** [comment]
https://www.google.com/search?q=opencre+org&sxsrf=AOaemvLd8B3NwY9apkXugkbNbCrWZAQOvA%3A1631359938030&source=hp&ei=wZM8Yfa-O8aHjLsP3tCEgA8&iflsig=ALs-wAMAAAAAYTyh0lKRAynumQyfA8KwCSlnvJ24tehm&oq=opencre+org&gs_lcp=Cgdnd3Mtd2l6EAM6BAgjECc6CwgAEIAEELEDEIMBOggIABCABBCxAzoOCC4QgAQQsQMQxwEQowI6BQgAEIAEOhEILhCABBCxAxDHARDRAxCTAjoOCC4QgAQQsQMQxwEQ0QM6CAguEIAEELEDOgsILhCABBDHARCjAjoUCC4QgAQQsQMQxwEQ0QMQyQMQkwI6BQgAEJIDOgsILhCABBDHARCvAToOCC4QgAQQxwEQrwEQkwI6BAgAEAo6BAgAEA06DQguEMcBEK8BEA0QkwI6BggAEA0QHjoICAAQCBANEB5QqgJY4Blgnh1oAHAAeACAAbQDiAHYDpIBCTQuNC4yLjAuMZgBAKABAQ&sclient=gws-wiz&ved=0ahUKEwi2o-qs6fbyAhXGA2MBHV4oAfAQ4dUDCAg&uact=5
