### ISSUE TITLE
Ensure reliability, performance ,security

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#47]
Please ensure that opencre frontend, backend are reliable (high availability, resistent against dos issues), secure (availability and integrity)  and performant (under high load when gaining popularity or at peeks (press launch), and dos).
When in doubt, can we make sure that we have a plan to upgrade or transition to another program or provider in case issues arise.

**Comment by northdpole** [comment]
The backend is a postgres database, our queries could be more performant but i don't expect them to bring down a full postgres instance.

I upgraded Heroku to a paid version so this should bring us more reliable and available infra.
I don't expect people to want to DoS a small website, a hug of death(a high ammount of legitimate requests) is a possibility but mitigating that requires CDNs and other very expensive solutions that are not applicable yet
