### ISSUE TITLE
Setup collaboration/feedback options for the community

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#48]
Spyros I know that you have specific good ideas about this. This is my stab at what I think is required: At launch it's important for the community to share input and provide suggestions immediately, particularly for the data. It requires that the source data is provided in such a way that people can find the data that they have suggestions for and suggest changes. 
Processing changes directly to production is not high priority I guess, but registering input and comments is important.

**Comment by northdpole** [comment]
data is located in /cres/ which involves both an export of the documents as yaml and a database. the community can open issues here for specific comments.

I could also create a contributing.md file to share details on how to contribute to the proejct

**Comment by robvanderveer** [comment]
That's a good idea: provide some documentation, also in the readme.
