### ISSUE TITLE
Hierarchy jumps are not being imported

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#68]
558-807 for example has a hierachy 1, 2 and not a 3. It seems that is the reason that the link between that CRE and it's 'parents' are not being imported.
https://www.opencre.org/cre/558-807 has no 'is part of' and the particular cre is also not mentioned in the contains list of its parent https://www.opencre.org/cre/270-568

**Comment by northdpole** [comment]
ah, you're right, I didn't expect hierarchy jumps, i'll fix this in a few hours
