### ISSUE TITLE
Tags don't seem to work

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#69]
In the tag column for https://www.opencre.org/cre/268-088 is DOS, but it doesn't show.
Also I don't see tags for XSS and Injection. 
There is a topic for injection and it links to a top 10 entry, but injection does not link to any CREs.
Has the tag column not been imported? It basically is the same as the "other cre" column.
Also note that some tag cells have two entries, separated by commas

**Comment by northdpole** [comment]
tags exist in the database and get returned, they haven't been implemented in the frontend as the frontend doesn't have a search by tag functionality yet. I'll add them but they will only be plain text for now, not hyperlinks.
But they prove the point that we have tagged documents and they can easily be searched by tag when we implement the functionality
