### ISSUE TITLE
text search does not refresh search results after second search .

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#83]
see title

**Comment by northdpole** [comment]
this is likely bad caching, it's on me to fix, will be done by tomorrow morning

**Comment by northdpole** [comment]
likely fixed by disabling caching, @robvanderveer can you please double-check?

**Comment by robvanderveer** [comment]
I see no difference.

**Comment by northdpole** [comment]
fixed by #111
