### ISSUE TITLE
Nested views don't seem to be working for "related" items

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#87]

**Comment by robvanderveer** [comment]
Mees is removing the contains section from the nested view, which is probably going to fix those cyclic issues, so then the Related links can also have nested view enabled.

**Comment by robvanderveer** [comment]
Alright, that helps, thanks. I got the easy solution:
1. first of all, we are not interested in things that are related to things that are related. That's too weak. DO "related to" should not go further than one step.  In other words: a "related to" link can be nested, but  that nested views should skip "related to" links.
Example: 
output encoding - is related to xss - which again is related to csp configuration.
In the CRE page we show output encoding, with "is related to" xss, but not the csp configuration below that.
2.second, we are less interested in what related things are part of. We don't show that either.
Numbers 1 and 2 can be seen as: when doing a nested view on a "related to" topic, leave out the part of and the related to. Because the 'contains' is already left out, the only remaining link type to show in the nested view for "is related: topics is 'linked'.

**Comment by robvanderveer** [comment]
Hi @Meess the cre page is looking great, but I do not yet see that related items have a nested view, for example on the well known https://www.opencre.org/cre/482-866 we see that personal data is not expanded. Otherwise it would have shown the linked items (mostly NIST 53 in this case).

**Comment by Meess** [comment]
@robvanderveer that is true, I canceled the pull request because I encountered still quite some bug with the nesting. So there would not be any changes related to this issue in production atm. But pull request is coming in a sec for the fix
