### ISSUE TITLE
See how we can be found with Google :/.  Mees suggests meta tags. What else?

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/common-requirement-enumeration#96]

**Comment by northdpole** [comment]
[this query](https://www.google.com/search?q=open+cre&source=hp&ei=JNkQYryPFseS8gL-gqy4DA&iflsig=AHkkrS4AAAAAYhDnNOfIn3_oK1iZZPSfMtU9qZcr4zUh&ved=0ahUKEwi8scyq2Yv2AhVHiVwKHX4BC8cQ4dUDCAg&uact=5&oq=open+cre&gs_lcp=Cgdnd3Mtd2l6EAMyCwguEIAEEMcBEK8BMgUIABCABDINCC4QgAQQxwEQrwEQCjIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6DggAEI8BEOoCEIwDEOUCOg4ILhCABBCxAxDHARCjAjoICAAQgAQQsQM6CAguEIAEELEDOggIABCxAxCDAToICC4QsQMQgwE6EQguEIAEELEDEIMBEMcBEK8BOhEILhCABBCxAxCDARDHARCjAjoLCAAQgAQQsQMQgwE6DgguEIAEELEDEMcBENEDOhEILhCABBCxAxCDARDHARDRAzoLCC4QgAQQxwEQ0QM6FAguEIAEELEDEIMBEMcBENEDEMkDOgUIABCSAzoQCC4QgAQQxwEQ0QMQyQMQCjoNCC4QgAQQxwEQ0QMQCjoICAAQgAQQyQM6BQgAELEDUM4HWOgbYNkcaAJwAHgAgAFKiAHmA5IBATmYAQCgAQGwAQo&sclient=gws-wiz) gives me opencre.org as the first result
